# Generated by Django 5.2 on 2025-08-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
