# Generated by Django 5.2.4 on 2025-08-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
