# Generated by Django 5.2.4 on 2025-08-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_testimonial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
