# Generated by Django 5.2.4 on 2025-08-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_testimonial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
